### ISSUE TITLE
Requested Updates

### ISSUE THREAD

**Issue by jonathankwhitmer** [MICCoM/SSAGES-site#10]
Add SSAGES and CoPSS-related papers to the publications page. This includes all works which utilize algorithms and analysis developed for the codes, even if not yet publically released. Citations should have full names of all contributors and include MICCoM project members in bold.

**Comment by cbezik** [comment]
@jonathankwhitmer Have you got any papers on your side you'd like me to include?  Please let me know.  @jjdepablo is going to update me with SSAGES papers from our end, and I'm also about to add Xikai's COPSS papers.

**Comment by jonathankwhitmer** [comment]
I do; I'll send you a copy offline.

**Comment by cbezik** [comment]
I think this one is good to go - please reopen if anyone objects.
